In [34]:

import numpy as np


In [35]:
content = np.loadtxt('data1.txt').astype(int)
print("\nContent in file1.txt:\n")
# print(content[:-1,:])
print(content)


Content in file1.txt:

[[ 0  0  0 ...  0  0  0]
 [62 62 63 ... 36 44  1]
 [65 63 66 ... 37 36  1]
 ...
 [71 75 74 ... 48 48  1]
 [73 66 68 ... 48 50  1]
 [71 74 73 ... 51 47  1]]


In [36]:
# Read comma separated data
def splitRawData(data):
    X, y = data[:, 0:-1], data[:, -1]

    if len(X.shape)==1:
        X = np.c_[X] # convert to a column vector
    
    y = np.c_[y] #convert to a column vector

    return X,y



data = np.loadtxt('data1.txt').astype(int)

X,y = splitRawData(data)
m = y.shape[0] # no of training data set
n = X.shape[1] # no of features

print(m,n)
print(y)

46 4800
[[0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
